### ISSUE TITLE
Is it working on GS66 10SF

### ISSUE THREAD

**Issue by shaemi** [zhujinle/MSI-GS66-Stealth-OC-Hackintosh#3]
Hello. is it working on MSI GS66 10SF?
with i7-10750H and RTX 2070

**Comment by Matthewenderle** [comment]
worked on mine like two years back. I don't have it installed anymore.

**Comment by zhujinle** [comment]
Work fine on GS66 664CN i7-10870H and RTX 2060
all NVIDIA gpu will be disabled, so in theory there is no difference
